spring:
  datasource:
    url: ${FILMORATE_DB_URL}
    username: ${FILMORATE_DB_USERNAME}
    password: ${FILMORATE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        security: debug



